services:
  sonoplay:
    build: .
    container_name: sonoplay
    network_mode: host
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    volumes:
      - sonoplay-config:/config

volumes:
  sonoplay-config:
