services:
  sonoplex:
    build: .
    container_name: sonoplex
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - sonoplex-config:/config

volumes:
  sonoplex-config: